project:
  type: book

book:
  title: "TransProPyBook"
  author: "Dongyue Yu"
  favicon: TransProPy_logo.png
  description: TransProPy is a Python package that is part of the TransPro series under the SuperOmics framework.
  keyword: TransProPy, DL, data science, data engineering
  url: https://sssydysss.github.io/TransProPyBook/
  date: "2023/11/15"
  sidebar: 
    background: "#a6cedb"
    logo: TransProPy_logo.png
    search: true
  repo-url: https://github.com/SSSYDYSSS/TransProPyBook
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  image: TransProPy_logo.png
  comments:
    giscus:
      repo: SSSYDYSSS/TransProPyBook
  open-graph:
    image: https://github.com/SSSYDYSSS/TransProPyBook/blob/main/TransProPy_logo.png
    description: Python package TransProPy.

  
  chapters:
    - index.qmd
    - UtilsFunction1.qmd
    - UtilsFunction2.qmd
    - UtilsFunction3.qmd
    - MACFCmain.qmd
    - NewMACFCmain.qmd
    - AutogluonTimeLimit.qmd
    - AutoGluonSelectML.qmd
    - AutoFeatureSelection.qmd
    - funkyheatmap.qmd
    - Percentage Stacked Line Bar Chart.qmd
    - Ridge Plot.qmd
    - CFD FullGSEA.qmd
    - ANKRD35 FullGSEA.qmd
    - ALOXE3 FullGSEA.qmd
    - GeneCount and GseaNES.qmd
    - ALL GENE LINE BAR.qmd
    - Seprate All GSEA.qmd
    - VennNetwork core enrichment.qmd
    - CircosBar core enrichment.qmd
    - Contact.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    css: custom.css
    backgroundcolor: "#eff7f8"

