# References 

::: {.refs}
>- <a href="https://academic.oup.com/bib/article-abstract/23/2/bbac029/6536295?redirectedFrom=fulltext&login=false" style="color: #43799a; font-weight: bold;">Su,Y., Du,K., Wang,J., Wei,J. and Liu,J. (2022) Multi-variable AUC for sifting complementary features and its biomedical application. Briefings in Bioinformatics, 23, bbac029.</a>
>
>- <a href="https://arxiv.org/abs/2003.06505" style="color: #43799a; font-weight: bold;">Erickson, N., Mueller, J., Shirkov, A., Zhang, H., Larroy, P., Li, M., & Smola, A. (2020). AutoGluon-Tabular: Robust and Accurate AutoML for Structured Data. arXiv preprint arXiv:2003.06505.</a>
>
>- <a href="https://arxiv.org/abs/2006.14284" style="color: #43799a; font-weight: bold;">Fakoor, R., Mueller, J., Erickson, N., Chaudhari, P., & Smola, A. J. (2020). Fast, Accurate, and Simple Models for Tabular Data via Augmented Distillation. arXiv preprint arXiv:2006.14284. </a>
>
>- <a href="https://openreview.net/forum?id=OHAIVOOl7Vl" style="color: #43799a; font-weight: bold;">Shi, X., Mueller, J., Erickson, N., Li, M., & Smola, A. (2021). Multimodal AutoML on Structured Tables with Text Fields. In AutoML@ICML 2021. </a>
>- <a href="https://aws.amazon.com/blogs/opensource/machine-learning-with-autogluon-an-open-source-automl-library/" style="color: #43799a; font-weight: bold;">Prasanna, S. (2020, March 31). Machine learning with AutoGluon, an open source AutoML library. AWS Open Source Blog. </a>
>
>- <a href="https://medium.com/@zhanghang0704/image-classification-on-kaggle-using-autogluon-fc896e74d7e8" style="color: #43799a; font-weight: bold;">Sun, Y., Wu, C., Zhang, Z., He, T., Mueller, J., & Zhang, H. (n.d.). (2020). Image classification on Kaggle using AutoGluon. Medium.</a>
>
>- <a href="https://towardsdatascience.com/autogluon-deep-learning-automl-5cdb4e2388ec" style="color: #43799a; font-weight: bold;">Erickson, N., Mueller, J., Zhang, H., & Kamakoti, B. (2019). AutoGluon: Deep Learning AutoML. Medium.</a>
>
>- <a href="https://auto.gluon.ai/0.1.0/api/autogluon.predictor.html?highlight=num_bag_folds" style="color: #43799a; font-weight: bold;">AutoGluon Predictors --AutoGluon Documentation 0.1.0 documentation</a>
>
:::





::: {.callout-note}
This manual is meticulously crafted to elaborate on the principles of the referenced functions, with an emphasis on the methods and objectives users should be cognizant of when utilizing these functions. It is designed to foster a thorough understanding and facilitate the adaptation of this Python package. References to the algorithms that are employed or adapted are presented as mentioned above. 

Should there be any omissions in the cited references that are significantly related to the content discussed herein, we would be **immensely grateful** to be informed by **our esteemed users**. Additionally, we sincerely apologize for any imperfections that may exist within this manual.
:::

